stages:
    preprocess:
      deps: 
        - ./src/main/scripts/preprocess.py
        - ./data/train.csv
      params:
        - preprocess.pca.n_components
      outs: 
        - data/preprocess
      cmd: python src/main/scripts/preprocess.py data/test
    train:
      deps: 
        - ./src/main/scripts/train.py
        - data/preprocess
      outs: 
        - data/test
        - model.pkl
      cmd: python src/main/scripts/train.py data/preprocess
    evaluation:
      deps: 
        - data/test
        - model.pkl
        - ./src/main/scripts/evaluation.py
      outs: 
        # - plot.png
        - metrics.txt
      metrics:
      - evaluation.json:
          cache: false
      cmd: python src/main/scripts/evaluation.py model.pkl data/test
