name: train-my-model
 
on: push
 
jobs:
  run:
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v2
 
      - uses: iterative/setup-cml@v1
      - uses: iterative/setup-dvc@v1

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Execute pipeline dvc
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -U pip
          pip3 install -r src/main/requirements.txt
          dvc params diff --md >> report.md
          dvc repro

      - name: Show Evaluation
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch --prune
          dvc metrics diff --show-md develop >> report.md
          cml publish plot.png --md >> report.md
          cml send-comment report.md