name: Slash Command Dispatch
on: issue_comment
jobs:
  check_comments:
    name: Check comments for /test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      - name: Show Evaluation
        run: |
          echo "test"
    